"""empty message

Revision ID: ae736f9e6117
Revises: 6959c97750c6
Create Date: 2024-04-25 00:00:55.332405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae736f9e6117'
down_revision = '6959c97750c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=700), nullable=False),
    sa.Column('email', sa.String(length=700), nullable=False),
    sa.Column('password', sa.String(length=700), nullable=False),
    sa.Column('bad_user_name', sa.String(length=700), nullable=False),
    sa.Column('bad_email', sa.String(length=700), nullable=False),
    sa.Column('bad_password', sa.String(length=700), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Submissions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Submissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=700), nullable=False),
    sa.Column('email', sa.VARCHAR(length=700), nullable=False),
    sa.Column('password', sa.VARCHAR(length=700), nullable=False),
    sa.Column('bad_user_name', sa.VARCHAR(length=700), nullable=False),
    sa.Column('bad_email', sa.VARCHAR(length=700), nullable=False),
    sa.Column('bad_password', sa.VARCHAR(length=700), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('todo')
    # ### end Alembic commands ###
